import { test } from 'node:test';
import assert from 'node:assert/strict';
import {calculateSale,summarizeSales} from '../lib/finance.ts';
import type {Sale,CostRecord} from '../lib/finance.ts';
const sale:Sale={id:'s',orderId:'o',accountId:'a',sku:'001',title:'Produto',date:'2026-09-10',quantity:2,costQuantity:2,revenueCents:20000,feeCents:3000,shippingCents:1000,otherCents:0,status:'paid'};
const cost:CostRecord={id:'c',accountId:'a',sku:'001',description:'Produto',unitCost:50,taxValue:5,taxType:'unit',taxTreatment:'included',validFrom:'2026-09-01',importedAt:'2026-09-11T00:00:00Z',importId:'i'};
test('imposto incluído não é deduzido novamente',()=>assert.equal(calculateSale(sale,[cost]).contributionCents,6000));
test('imposto adicional unitário usa a quantidade',()=>assert.equal(calculateSale(sale,[{...cost,taxTreatment:'additional'}]).contributionCents,5000));
test('imposto percentual usa receita líquida da linha',()=>assert.equal(calculateSale(sale,[{...cost,taxType:'percent',taxValue:6,taxTreatment:'additional'}]).contributionCents,4800));
test('ausência de custo não produz lucro artificial',()=>assert.equal(calculateSale(sale,[]).contributionCents,null));
test('imposto não classificado impede margem completa',()=>assert.equal(calculateSale(sale,[{...cost,taxTreatment:'unknown'}]).contributionCents,null));
test('imposto vazio difere de zero declarado',()=>{assert.equal(calculateSale(sale,[{...cost,taxValue:null,taxTreatment:'additional'}]).contributionCents,null);assert.equal(calculateSale(sale,[{...cost,taxValue:0,taxTreatment:'additional'}]).contributionCents,6000)});
test('custo futuro ou de outra conta não altera o passado',()=>assert.equal(calculateSale(sale,[{...cost,validFrom:'2026-09-12'},{...cost,accountId:'other'}]).contributionCents,null));
test('entre custos vigentes usa o mais recente',()=>assert.equal(calculateSale(sale,[cost,{...cost,unitCost:60,validFrom:'2026-09-09'}]).contributionCents,4000));
test('mesma vigência respeita última revisão importada',()=>assert.equal(calculateSale(sale,[cost,{...cost,unitCost:70,importedAt:'2026-09-12T00:00:00Z'}]).contributionCents,2000));
test('arredonda custo depois de multiplicar unidades',()=>assert.equal(calculateSale({...sale,quantity:3,costQuantity:3},[{...cost,unitCost:10.3333}]).costCents,3100));
test('cobertura informa receita sem custo e margem não é média simples',()=>{const r=summarizeSales([sale,{...sale,id:'x',orderId:'y',sku:'unknown',revenueCents:10000}],[cost]);assert.equal(r.revenueCents,30000);assert.equal(r.coveredRevenueCents,20000);assert.equal(r.contributionCents,6000);assert.equal(r.margin,30);assert.equal(r.orders,2)});
test('reembolso sem recuperação do estoque preserva custo consumido',()=>assert.equal(calculateSale({...sale,status:'refunded',revenueCents:0,feeCents:0,shippingCents:1000},[cost]).contributionCents,-11000));
