import {test} from 'node:test';import assert from 'node:assert/strict';import * as XLSX from 'xlsx';
import {readWorkbook} from '../lib/workbook.ts';import {normalizeRows} from '../lib/imports.ts';
const mapping={sku:0,description:1,cost:2,tax:3};const options={accountId:'a',validFrom:'2026-09-01',taxType:'unit' as const,taxTreatment:'included' as const};
function encode(sheet:XLSX.WorkSheet):ArrayBuffer{const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Custos');return XLSX.write(book,{type:'array',bookType:'xlsx',compression:true});}
test('XLSX mantém 12.345 como custo decimal, sem virar 12345',()=>{const sheet=XLSX.utils.aoa_to_sheet([['SKU','Produto','Custo','Imposto'],['001','A',12.345,0]]);const rows=readWorkbook(encode(sheet),'custos.xlsx')[0].rows.slice(1);assert.equal(normalizeRows(rows,mapping,options).records[0]?.unitCost,12.345)});
test('formatação de duas casas não arredonda o custo armazenado',()=>{const sheet=XLSX.utils.aoa_to_sheet([['SKU','Produto','Custo','Imposto'],['001','A',10.3333,0]]);sheet.C2.z='0.00';assert.equal(normalizeRows(readWorkbook(encode(sheet),'custos.xlsx')[0].rows.slice(1),mapping,options).records[0]?.unitCost,10.3333)});
test('formato numérico de SKU preserva zeros à esquerda',()=>{const sheet=XLSX.utils.aoa_to_sheet([['SKU','Produto','Custo','Imposto'],[123,'A',20,0]]);sheet.A2.z='000000';assert.equal(normalizeRows(readWorkbook(encode(sheet),'custos.xlsx')[0].rows.slice(1),mapping,options).records[0]?.sku,'000123')});
test('percentual Excel usa valor integral sem perder precisão',()=>{const sheet=XLSX.utils.aoa_to_sheet([['SKU','Produto','Custo','Imposto'],['001','A',20,.061234]]);sheet.D2.z='0.00%';assert.equal(normalizeRows(readWorkbook(encode(sheet),'custos.xlsx')[0].rows.slice(1),mapping,{...options,taxType:'percent'}).records[0]?.taxValue,6.1234)});
test('célula percentual não vira imposto unitário sem aviso',()=>{const sheet=XLSX.utils.aoa_to_sheet([['SKU','Produto','Custo','Imposto'],['001','A',20,.06]]);sheet.D2.z='0%';assert.equal(normalizeRows(readWorkbook(encode(sheet),'custos.xlsx')[0].rows.slice(1),mapping,options).issues.length,1)});
test('planilha com linhas além do limite não é truncada silenciosamente',()=>{const sheet=XLSX.utils.aoa_to_sheet([['SKU','Produto','Custo','Imposto'],['001','A',20,0]]);XLSX.utils.sheet_add_aoa(sheet,[['002','B',30,0]],{origin:'A5101'});assert.throws(()=>readWorkbook(encode(sheet),'custos.xlsx'),/linhas|limite/i)});
