'use client';
import {useState,useEffect,useMemo,useCallback,useRef} from 'react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Toaster} from '@/components/ui/sonner';import {toast} from 'sonner';
import {LayoutDashboard,ShoppingBag,Package,FileSpreadsheet,Store,ShieldCheck,Plus,Upload,ChevronRight,Info,Unplug,LoaderCircle,Layers,ArrowRight} from 'lucide-react';
import {Choice} from './commerce-controls';import {Overview,SalesView,ProductsView} from './finance-views';import {CostImporter} from './cost-importer';import {CostsView} from './costs-view';import {demoWorkspace,emptyWorkspace,type Workspace,type Account} from '@/lib/demo';
type View='overview'|'sales'|'products'|'costs'|'accounts';
const navigation=[{id:'overview',label:'Visão geral',icon:LayoutDashboard},{id:'sales',label:'Vendas',icon:ShoppingBag},{id:'products',label:'Produtos e margem',icon:Package},{id:'costs',label:'Custos e impostos',icon:FileSpreadsheet},{id:'accounts',label:'Minhas contas',icon:Store}] as const;
function Nav({view,onView,userName}:{view:View;onView:(v:View)=>void;userName:string}){const {setOpenMobile}=useSidebar();return <Sidebar><SidebarHeader className="brand-header"><div className="brand-mark"><Layers size={24}/></div><div className="brand-name">central<span>DE VENDAS</span></div></SidebarHeader><SidebarContent><div className="workspace-label"><span className="workspace-avatar">LV</span><div>Minha operação<small>Mercado Livre</small></div><ChevronRight size={15}/></div><SidebarGroup className="navigation-group"><SidebarGroupLabel>GESTÃO</SidebarGroupLabel><SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{onView(n.id);setOpenMobile(false)}} className="nav-button"><n.icon/><span>{n.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><div className="next-phase"><span className="eyebrow">PRÓXIMOS MÓDULOS</span><p>Publicidade, insights<br/>e agente de IA.</p><span>Na sequência do núcleo financeiro</span></div></SidebarContent><SidebarFooter className="sidebar-footer"><div className="private-note"><ShieldCheck size={16}/><span>Seu espaço privado</span></div><div className="user-profile"><span>{(userName[0]||'L').toUpperCase()}</span><div><strong>{userName}</strong><small>Proprietário</small></div></div></SidebarFooter></Sidebar>}
export default function CommerceApp({userName,signedIn}:{userName:string;signedIn:boolean}){
 const [view,setView]=useState<View>('overview');const [demo,setDemo]=useState(true);const [real,setReal]=useState<Workspace>(emptyWorkspace);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [account,setAccount]=useState('all');const [period,setPeriod]=useState('30');const [importer,setImporter]=useState(false);const [accountDialog,setAccountDialog]=useState(false);const [afterAccount,setAfterAccount]=useState(false);const [name,setName]=useState('');const [saving,setSaving]=useState(false);const [accountError,setAccountError]=useState('');const first=useRef(true);const sample=useMemo(()=>demoWorkspace(),[]);
 const load=useCallback(async()=>{setLoadError('');try{if(!signedIn){setLoading(false);return;}const r=await fetch('/api/workspace');const data=await r.json() as Workspace & {error?:string};if(!r.ok)throw Error(data.error);setReal(data);if(first.current&&data.accounts.length)setDemo(false);first.current=false;}catch(e){setLoadError(e instanceof Error?e.message:'Não foi possível carregar sua operação.')}finally{setLoading(false)}},[signedIn]);
 useEffect(()=>{void load();const hash=window.location.hash.slice(1);if(navigation.some(n=>n.id===hash))setView(hash as View)},[load]);
 const data=demo?sample:real;const costs=data.costs.filter(c=>account==='all'||c.accountId===account);const sales=data.sales.filter(s=>{const from=new Date();from.setDate(from.getDate()-(Number(period)-1));return (account==='all'||s.accountId===account)&&s.date>=from.toISOString().slice(0,10)});
 function changeView(v:View){setView(v);window.history.replaceState(null,'',`#${v}`)}
 function switchMode(v:string){setDemo(v==='demo');setAccount('all')}
 function startImport(){if(!signedIn){window.location.href='/signin-with-chatgpt?return_to=%2F%23costs';return;}setDemo(false);setAccount('all');changeView('costs');if(!real.accounts.length){setAfterAccount(true);setAccountDialog(true)}else setImporter(true)}
 async function addAccount(){setSaving(true);setAccountError('');try{const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);await load();setDemo(false);setAccount('all');setAccountDialog(false);setName('');toast.success('Conta de trabalho criada.');if(afterAccount){setImporter(true);setAfterAccount(false)}}catch(e){setAccountError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSaving(false)}}
 return <SidebarProvider style={{'--sidebar-width':'248px'} as React.CSSProperties}><Nav view={view} onView={changeView} userName={userName}/><SidebarInset className="app-main"><header className="topbar"><div className="topbar-path"><SidebarTrigger aria-label="Abrir menu"/><span>Minha operação</span><ChevronRight size={14}/><strong>{navigation.find(n=>n.id===view)?.label}</strong></div><div className="topbar-right"><span className="private-badge"><ShieldCheck size={14}/>Privado</span><div className="top-avatar">{(userName[0]||'L').toUpperCase()}</div></div></header><main className="workspace-main"><div className="page-heading"><div><span className="eyebrow">MERCADO LIVRE</span><h1>{navigation.find(n=>n.id===view)?.label}</h1><p>{view==='overview'?'Acompanhe o resultado da sua operação.':view==='costs'?'Custos confiáveis. Impostos sem duplicidade.':view==='sales'?'Cada venda, com seus custos à vista.':view==='products'?'Entenda quais produtos contribuem para o resultado.':'Organize as contas da sua operação.'}</p></div><Button className="primary-action" onClick={startImport}><Upload size={16}/>Importar custos</Button></div>
 <div className="control-bar"><Tabs value={demo?'demo':'real'} onValueChange={switchMode}><TabsList className="mode-tabs"><TabsTrigger value="demo">Demonstração</TabsTrigger><TabsTrigger value="real">Minha operação</TabsTrigger></TabsList></Tabs><div className="filters"><Choice value={account} onChange={setAccount} label="Filtrar por conta" options={[{value:'all',label:'Todas as contas'},...data.accounts.map(a=>({value:a.id,label:a.name}))]}/>{['overview','sales','products'].includes(view)&&<Choice value={period} onChange={setPeriod} label="Período" options={[{value:'30',label:'Últimos 30 dias'},{value:'14',label:'Últimos 14 dias'},{value:'7',label:'Últimos 7 dias'}]}/>}</div></div>
 {demo?<div className="demo-banner"><Info size={16}/><span>Você está explorando dados de exemplo. Suas planilhas ficam em <strong>Minha operação</strong>.</span><button onClick={()=>switchMode('real')}>Ir para minha operação <ArrowRight size={14}/></button></div>:<div className="real-banner"><ShieldCheck size={15}/><span>Seus arquivos e custos · conexão de vendas ainda não ativada</span></div>}
 {!demo&&loading?<div className="panel loading-panel"><LoaderCircle className="animate-spin"/>Carregando sua operação…</div>:!demo&&!signedIn?<section className="panel empty-onboarding"><h2>Entre para salvar seus custos</h2><p>O acesso mantém seus documentos privados e disponíveis quando você voltar.</p><Button asChild><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar na minha operação <ArrowRight/></a></Button></section>:!demo&&loadError?<section className="panel error-panel"><h2>Não foi possível carregar os dados</h2><p>{loadError}</p><Button onClick={()=>void load()}>Tentar novamente</Button></section>:<>{view==='overview'&&<Overview sales={sales} costs={costs} demo={demo} onProducts={()=>changeView('products')} onCosts={()=>changeView('costs')} onAccounts={()=>changeView('accounts')}/>} {view==='sales'&&<SalesView sales={sales} costs={costs} accounts={data.accounts}/>} {view==='products'&&<ProductsView sales={sales} costs={costs} accounts={data.accounts}/>} {view==='costs'&&<CostsView costs={costs} imports={data.imports.filter(i=>account==='all'||i.accountId===account)} accounts={data.accounts} demo={demo} onImport={startImport} onReload={load}/>} {view==='accounts'&&<AccountsView accounts={data.accounts} demo={demo} onAdd={()=>{if(!signedIn){window.location.href='/signin-with-chatgpt?return_to=%2F%23accounts';return;}setAfterAccount(false);setAccountDialog(true)}}/>}</>}
 <footer className="workspace-footer"><span>Central de Vendas</span><span>{demo?'Dados ilustrativos · nenhuma conta conectada':'Espaço privado · dados de vendas aguardando integração'}</span></footer></main></SidebarInset><Toaster position="bottom-right"/>{importer&&<CostImporter open onClose={()=>setImporter(false)} accounts={real.accounts} onSuccess={async()=>{await load();setDemo(false);changeView('costs')}}/>}<Dialog open={accountDialog} onOpenChange={setAccountDialog}><DialogContent><DialogHeader><DialogTitle>Adicionar conta de trabalho</DialogTitle><DialogDescription>Defina um nome para organizar as planilhas de custos. Isso ainda não conecta uma conta ao Mercado Livre.</DialogDescription></DialogHeader><label className="form-label">Nome da conta<Input autoFocus value={name} placeholder="Ex.: Loja principal" maxLength={80} onChange={e=>setName(e.target.value)}/></label>{accountError&&<p className="error-box" role="alert">{accountError}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={()=>setAccountDialog(false)}>Cancelar</Button><Button disabled={saving||name.trim().length<2} onClick={()=>void addAccount()}>{saving?<LoaderCircle className="animate-spin"/>:<Plus/>}Criar conta</Button></div></DialogContent></Dialog></SidebarProvider>;
}
function AccountsView({accounts,demo,onAdd}:{accounts:Account[];demo:boolean;onAdd:()=>void}){return <><section className="accounts-heading"><div><h2>Uma visão para todas as suas contas</h2><p>Organize os custos de cada operação separadamente.</p></div><Button onClick={onAdd}><Plus/>Adicionar conta</Button></section><div className="account-grid">{accounts.map(a=><section className="panel account-card" key={a.id}><div className="account-card-top"><span className="store-icon"><Store size={26}/></span><span className="neutral-pill">{demo?'Exemplo':'Aguardando integração'}</span></div><h2>{a.name}</h2><p>Mercado Livre · Brasil</p><div className="account-status"><Unplug size={16}/>{demo?'Conta ilustrativa':'Conta de trabalho cadastrada'}</div><p className="note-text">{demo?'Os valores desta conta são fictícios.':'Você já pode importar os custos desta conta. A conexão de vendas será configurada na etapa de integração.'}</p></section>)}<button className="add-account-card" onClick={onAdd}><span><Plus size={24}/></span><strong>Adicionar uma conta</strong><p>Prepare sua próxima operação</p></button></div><section className="connection-note"><ShieldCheck size={22}/><div><h3>Conexão oficial com o Mercado Livre</h3><p>A próxima etapa exige cadastrar a aplicação e autorizar cada vendedor. O cadastro acima organiza os arquivos; ele não acessa vendas nem altera sua conta.</p></div></section></>}
