'use client';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {useReactTable,getCoreRowModel,getSortedRowModel,getPaginationRowModel,flexRender,type ColumnDef,type SortingState} from '@tanstack/react-table';
import {useState} from 'react';import {Button} from '@/components/ui/button';import {ArrowUpDown,ChevronLeft,ChevronRight} from 'lucide-react';
export function Choice({value,onChange,options,label,className=''}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string;className?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className={`choice ${className}`}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function DataTable<T>({data,columns,empty='Nenhum registro encontrado.'}:{data:T[];columns:ColumnDef<T,unknown>[];empty?:string}){
 const [sorting,setSorting]=useState<SortingState>([]);const table=useReactTable({data,columns,state:{sorting},onSortingChange:setSorting,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),initialState:{pagination:{pageSize:10}}});
 return <><Table><TableHeader>{table.getHeaderGroups().map(g=><TableRow key={g.id}>{g.headers.map(h=><TableHead key={h.id} aria-sort={h.column.getIsSorted()==='asc'?'ascending':h.column.getIsSorted()==='desc'?'descending':undefined}>{h.column.getCanSort()?<button className="table-sort" onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}<ArrowUpDown size={12}/></button>:flexRender(h.column.columnDef.header,h.getContext())}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.length?table.getRowModel().rows.map(row=><TableRow key={row.id}>{row.getVisibleCells().map(cell=><TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={columns.length} className="empty-table">{empty}</TableCell></TableRow>}</TableBody></Table><div className="table-footer"><span>{data.length.toLocaleString('pt-BR')} registros</span>{data.length>10&&<div className="inline-actions"><span>Página {table.getState().pagination.pageIndex+1} de {table.getPageCount()}</span><Button size="icon" variant="outline" aria-label="Página anterior" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}><ChevronLeft/></Button><Button size="icon" variant="outline" aria-label="Próxima página" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}><ChevronRight/></Button></div>}</div></>;
}
