'use client';
import {useState,useEffect,useMemo} from 'react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Toaster} from '@/components/ui/sonner';import {toast} from 'sonner';
import {LayoutDashboard,ShoppingBag,Package,Store,ShieldCheck,Plus,ChevronRight,Info,Unplug,LoaderCircle,Layers,ArrowRight,TriangleAlert,Warehouse,Megaphone} from 'lucide-react';
import {AdvertisingView} from './advertising-view';
import {MeliAccounts} from './meli-accounts';
import {visiblePoll} from '@/lib/visible-poll';
import {requestCoordinator} from '@/lib/request-coordinator';
import {periodStart} from '@/lib/dates';
import {Choice} from './commerce-controls';import {Overview,SalesView} from './finance-views';import {AdProfilesView} from './ad-profiles-view';import {PendingView} from './pending-view';import {FullExpensesView} from './full-expenses-view';import {demoWorkspace,emptyWorkspace,type Workspace,type Account} from '@/lib/demo';
type View='overview'|'sales'|'pending'|'ads'|'advertising'|'full-expenses'|'accounts';
const navigation=[{id:'overview',label:'Visão geral',icon:LayoutDashboard},{id:'sales',label:'Vendas',icon:ShoppingBag},{id:'pending',label:'Pendências',icon:TriangleAlert},{id:'ads',label:'Anúncios',icon:Package},{id:'advertising',label:'Publicidade',icon:Megaphone},{id:'full-expenses',label:'Despesas Full',icon:Warehouse},{id:'accounts',label:'Minhas contas',icon:Store}] as const;
function Nav({view,onView,userName,pendingCount}:{view:View;onView:(v:View)=>void;userName:string;pendingCount:number}){const {setOpenMobile}=useSidebar();return <Sidebar><SidebarHeader className="brand-header"><div className="brand-mark"><Layers size={24}/></div><div className="brand-name">central<span>DE VENDAS</span></div></SidebarHeader><SidebarContent><div className="workspace-label"><span className="workspace-avatar">LV</span><div>Minha operação<small>Mercado Livre</small></div><ChevronRight size={15}/></div><SidebarGroup className="navigation-group"><SidebarGroupLabel>GESTÃO</SidebarGroupLabel><SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{onView(n.id);setOpenMobile(false)}} className="nav-button"><n.icon/><span>{n.label}</span>{n.id==='pending'&&pendingCount>0&&<span className="nav-count">{pendingCount>99?'99+':pendingCount}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><div className="next-phase"><span className="eyebrow">PRÓXIMOS MÓDULOS</span><p>Insights e<br/>agente de IA.</p><span>Na sequência do núcleo financeiro</span></div></SidebarContent><SidebarFooter className="sidebar-footer"><div className="private-note"><ShieldCheck size={16}/><span>Seu espaço privado</span></div><div className="user-profile"><span>{(userName[0]||'L').toUpperCase()}</span><div><strong>{userName}</strong><small>Proprietário</small></div></div></SidebarFooter></Sidebar>}
export default function CommerceApp({userName,signedIn}:{userName:string;signedIn:boolean}){
 const [view,setView]=useState<View>('overview');const [demoChoice,setDemo]=useState<boolean|null>(null);const [real,setReal]=useState<Workspace>(emptyWorkspace);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [account,setAccount]=useState('all');const [period,setPeriod]=useState('30');const [adTarget,setAdTarget]=useState<{accountId:string;itemId:string;variationId?:string|null}|null>(null);const [accountDialog,setAccountDialog]=useState(false);const [name,setName]=useState('');const [saving,setSaving]=useState(false);const [accountError,setAccountError]=useState('');const sample=useMemo(()=>demoWorkspace(),[]);
 // Until the owner picks a mode, show the demo only while there is no real account to show.
 const demo=demoChoice??(loading||real.accounts.length===0);
 const coordinator=useMemo(()=>requestCoordinator(async()=>{setLoadError('');try{if(!signedIn){setLoading(false);return;}const r=await fetch('/api/workspace');const data=await r.json() as Workspace & {error?:string};if(!r.ok)throw Error(data.error);setReal(data);}catch(e){setLoadError(e instanceof Error?e.message:'Não foi possível carregar sua operação.')}finally{setLoading(false)}}),[signedIn]);const load=coordinator.poll;const refresh=coordinator.refresh;
 // The URL hash only exists in the browser, so the initial view is read after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect -- syncs from window.location on mount
 useEffect(()=>{void load();const hash=window.location.hash.slice(1),target=hash==='products'||hash==='costs'?'ads':hash==='reconciliation'?'pending':hash;if(navigation.some(n=>n.id===target)){setView(target as View);if(target!==hash)window.history.replaceState(null,'',`#${target}`)}},[load]);
 useEffect(()=>{if(signedIn&&!demo)return visiblePoll(load)},[signedIn,demo,load]);
 const data=demo?sample:real;const costs=data.costs.filter(c=>account==='all'||c.accountId===account);const accountSales=data.sales.filter(s=>account==='all'||s.accountId===account);const from=periodStart(Number(period));const sales=accountSales.filter(s=>s.date>=from);const listings=data.listings.filter(item=>account==='all'||item.accountId===account);const pendingItems=data.pending.filter(item=>account==='all'||item.accountId===account);const adSpend=(data.adSpend??[]).filter(row=>(account==='all'||row.accountId===account)&&row.date>=from);const adsCostCents=adSpend.reduce((sum,row)=>sum+row.costCents,0);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- handles the Mercado Livre OAuth return once, after hydration
 useEffect(()=>{const url=new URL(window.location.href);if(url.searchParams.has('meli')){setDemo(false);setView('accounts');if(url.searchParams.get('meli')==='connected')toast.success('Conta conectada. Agora clique em Atualizar vendas.');else toast.error(url.searchParams.get('message')||'Não foi possível conectar.');url.searchParams.delete('meli');url.searchParams.delete('message');window.history.replaceState(null,'',url.pathname+url.search+url.hash)}},[]);
 function changeView(v:View){setView(v);window.history.replaceState(null,'',`#${v}`)}
 function switchMode(v:string){setDemo(v==='demo');setAccount('all')}
 async function addAccount(){setSaving(true);setAccountError('');try{const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);await refresh();setDemo(false);setAccount('all');setAccountDialog(false);setName('');toast.success('Conta de trabalho criada.')}catch(e){setAccountError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSaving(false)}}
 return <SidebarProvider style={{'--sidebar-width':'248px'} as React.CSSProperties}><Nav view={view} onView={changeView} userName={userName} pendingCount={pendingItems.length}/><SidebarInset className="app-main"><header className="topbar"><div className="topbar-path"><SidebarTrigger aria-label="Abrir menu"/><span>Minha operação</span><ChevronRight size={14}/><strong>{navigation.find(n=>n.id===view)?.label}</strong></div><div className="topbar-right"><span className="private-badge"><ShieldCheck size={14}/>Privado</span><div className="top-avatar">{(userName[0]||'L').toUpperCase()}</div></div></header><main className="workspace-main"><div className="page-heading"><div><span className="eyebrow">MERCADO LIVRE</span><h1>{navigation.find(n=>n.id===view)?.label}</h1><p>{view==='overview'?'Acompanhe o resultado da sua operação.':view==='sales'?'Cada venda, com suas fontes e resultado.':view==='pending'?'Resolva somente os dados que pedem sua decisão.':view==='ads'?'Cadastre custo e imposto uma vez em cada anúncio.':view==='advertising'?'Quanto o Mercado Ads custa e quanto sobra depois dele.':view==='full-expenses'?'Distribua o total mensal do demonstrativo Full.':'Organize as contas da sua operação.'}</p></div></div>
 <div className="control-bar"><Tabs value={demo?'demo':'real'} onValueChange={switchMode}><TabsList className="mode-tabs"><TabsTrigger value="demo">Demonstração</TabsTrigger><TabsTrigger value="real">Minha operação</TabsTrigger></TabsList></Tabs><div className="filters"><Choice value={account} onChange={setAccount} label="Filtrar por conta" options={[{value:'all',label:'Todas as contas'},...data.accounts.map(a=>({value:a.id,label:a.name}))]}/>{['overview','sales','advertising'].includes(view)&&<Choice value={period} onChange={setPeriod} label="Período" options={[{value:'30',label:'Últimos 30 dias'},{value:'14',label:'Últimos 14 dias'},{value:'7',label:'Últimos 7 dias'}]}/>}</div></div>
 {demo?<div className="demo-banner"><Info size={16}/><span>Você está explorando dados de exemplo. Seus cadastros reais ficam em <strong>Minha operação</strong>.</span><button onClick={()=>switchMode('real')}>Ir para minha operação <ArrowRight size={14}/></button></div>:<div className="real-banner"><ShieldCheck size={15}/><span>Dados automáticos do Mercado Livre · complete apenas as fichas que pedem atenção</span></div>}
 {!demo&&!!real.syncWarnings?.length&&<div className="warning-box">Atualização parcial: {real.syncWarnings.filter(w=>account==='all'||w.accountId===account).map(w=>w.name).join(', ')||'outras contas'}. <button className="text-action" onClick={()=>changeView('accounts')}>Retomar em Minhas contas</button></div>}
 {!demo&&loading?<div className="panel loading-panel"><LoaderCircle className="animate-spin"/>Carregando sua operação…</div>:!demo&&!signedIn?<section className="panel empty-onboarding"><h2>Entre para salvar suas fichas</h2><p>O acesso mantém seus dados privados e disponíveis quando você voltar.</p><Button asChild><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar na minha operação <ArrowRight/></a></Button></section>:!demo&&loadError?<section className="panel error-panel"><h2>Não foi possível carregar os dados</h2><p>{loadError}</p><Button onClick={()=>void refresh()}>Tentar novamente</Button></section>:<>{view==='overview'&&<Overview sales={sales} costs={costs} adsCostCents={adSpend.length?adsCostCents:null} onAdvertising={()=>changeView('advertising')} accounts={data.accounts} demo={demo} onAds={()=>changeView('ads')} onPending={()=>changeView('pending')} onAccounts={()=>changeView('accounts')}/>} {view==='sales'&&<SalesView sales={sales} costs={costs} accounts={data.accounts} corrections={data.saleCorrections}/>} {view==='pending'&&<PendingView pending={pendingItems} sales={accountSales} accounts={data.accounts} corrections={data.saleCorrections} demo={demo} onEditAd={item=>{if(item.itemId)setAdTarget({accountId:item.accountId,itemId:item.itemId,variationId:item.variationId});setAccount(item.accountId);changeView('ads')}} onOpenFull={()=>changeView('full-expenses')} onOpenSales={()=>changeView('sales')} onReviewMigration={()=>{changeView('ads');toast.info('Confira as fichas indicadas antes de ativar a nova projeção.')}} onReload={refresh}/>} {view==='ads'&&<AdProfilesView listings={listings} profiles={data.adProfiles} sales={accountSales} accounts={data.accounts} demo={demo} openTarget={adTarget} onReload={refresh}/>} {view==='advertising'&&<AdvertisingView spend={adSpend} status={(data.adsStatus??[]).filter(item=>account==='all'||item.accountId===account)} sales={sales} costs={costs} accounts={account==='all'?data.accounts:data.accounts.filter(item=>item.id===account)} listings={listings} demo={demo} onReload={refresh}/>} {view==='full-expenses'&&<FullExpensesView accounts={account==='all'?data.accounts:data.accounts.filter(item=>item.id===account)} closures={data.fullClosures.filter(item=>account==='all'||item.accountId===account)} demo={demo} onReload={refresh}/>} {view==='accounts'&&<AccountsSwitch accounts={data.accounts} demo={demo} onReload={refresh} onAdd={()=>{if(!signedIn){window.location.href='/signin-with-chatgpt?return_to=%2F%23accounts';return;}setAccountDialog(true)}}/>}</>}
 <footer className="workspace-footer"><span>Central de Vendas</span><span>{demo?'Dados ilustrativos · nenhuma conta conectada':'Espaço privado · painel atualizado a cada 15 segundos'}</span></footer></main></SidebarInset><Toaster position="bottom-right"/><Dialog open={accountDialog} onOpenChange={setAccountDialog}><DialogContent><DialogHeader><DialogTitle>Adicionar conta de trabalho</DialogTitle><DialogDescription>Defina um nome para organizar esta operação antes de conectar o vendedor do Mercado Livre.</DialogDescription></DialogHeader><label className="form-label">Nome da conta<Input autoFocus value={name} placeholder="Ex.: Loja principal" maxLength={80} onChange={e=>setName(e.target.value)}/></label>{accountError&&<p className="error-box" role="alert">{accountError}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={()=>setAccountDialog(false)}>Cancelar</Button><Button disabled={saving||name.trim().length<2} onClick={()=>void addAccount()}>{saving?<LoaderCircle className="animate-spin"/>:<Plus/>}Criar conta</Button></div></DialogContent></Dialog></SidebarProvider>;
}
function AccountsView({accounts,demo,onAdd}:{accounts:Account[];demo:boolean;onAdd:()=>void}){return <><section className="accounts-heading"><div><h2>Uma visão para todas as suas contas</h2><p>Organize anúncios, vendas e despesas de cada operação.</p></div><Button onClick={onAdd}><Plus/>Adicionar conta</Button></section><div className="account-grid">{accounts.map(a=><section className="panel account-card" key={a.id}><div className="account-card-top"><span className="store-icon"><Store size={26}/></span><span className="neutral-pill">{demo?'Exemplo':'Aguardando integração'}</span></div><h2>{a.name}</h2><p>Mercado Livre · Brasil</p><div className="account-status"><Unplug size={16}/>{demo?'Conta ilustrativa':'Conta de trabalho cadastrada'}</div><p className="note-text">{demo?'Os valores desta conta são fictícios.':'Conecte o vendedor para sincronizar anúncios e vendas. Depois, complete somente as fichas indicadas.'}</p></section>)}<button className="add-account-card" onClick={onAdd}><span><Plus size={24}/></span><strong>Adicionar uma conta</strong><p>Prepare sua próxima operação</p></button></div><section className="connection-note"><ShieldCheck size={22}/><div><h3>Conexão oficial com o Mercado Livre</h3><p>Em Minha operação, configure sua aplicação e autorize cada vendedor para consultar anúncios e vendas. As contas desta demonstração usam apenas dados ilustrativos.</p></div></section></>}

function AccountsSwitch({accounts,demo,onAdd,onReload}:{accounts:Account[];demo:boolean;onAdd:()=>void;onReload:()=>Promise<void>}){return demo?<AccountsView accounts={accounts} demo onAdd={onAdd}/>:<MeliAccounts accounts={accounts} onAdd={onAdd} onReload={onReload}/>;}
