'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {DataTable} from './commerce-controls';import type {Account,ImportBatch} from '@/lib/demo';import {money,type CostRecord} from '@/lib/finance';import {FileSpreadsheet,Plus,Download,History,Search,Trash2,Info} from 'lucide-react';import {toast} from 'sonner';
export function CostsView({costs,imports,accounts,demo,onImport,onReload}:{costs:CostRecord[];imports:ImportBatch[];accounts:Account[];demo:boolean;onImport:()=>void;onReload:()=>Promise<void>}){
 const [tab,setTab]=useState('products');const [query,setQuery]=useState('');const [withdraw,setWithdraw]=useState<ImportBatch|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const latest=Object.values([...costs].sort((a,b)=>b.validFrom.localeCompare(a.validFrom)||b.importedAt.localeCompare(a.importedAt)).reduce((a,c)=>{const key=c.accountId+'\0'+c.sku;if(!a[key])a[key]=c;return a},{} as Record<string,CostRecord>)).filter(c=>`${c.sku} ${c.description}`.toLowerCase().includes(query.toLowerCase()));
 async function remove(){if(!withdraw)return;setBusy(true);setError('');try{const r=await fetch(`/api/imports/${withdraw.id}`,{method:'DELETE'});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);await onReload();setWithdraw(null);toast.success('Lote retirado dos cálculos. Histórico preservado.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível retirar o lote.')}finally{setBusy(false)}}
 return <><section className="import-feature"><div className="file-feature-icon"><FileSpreadsheet size={32}/></div><div><span className="eyebrow">ARQUIVOS DO CITEL</span><h2>Seus custos, em um só lugar</h2><p>Importe a planilha, relacione as colunas e confira o imposto pago.</p></div><div className="import-feature-actions"><Button onClick={onImport}><Plus/>Nova importação</Button><a href="/modelo-custos.csv" download><Download size={14}/>Baixar modelo CSV</a></div></section><div className="cost-stats"><div><span>Produtos cadastrados</span><strong>{latest.length}</strong></div><div><span>Impostos a conferir</span><strong>{latest.filter(c=>c.taxTreatment==='unknown'||c.taxValue===null).length}</strong></div><div><span>Lotes ativos</span><strong>{demo?'Exemplo':imports.filter(i=>!i.withdrawnAt).length}</strong></div></div>
 <section className="panel"><div className="panel-heading"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="products">Custos por produto</TabsTrigger><TabsTrigger value="history"><History size={15}/>Histórico</TabsTrigger></TabsList></Tabs>{tab==='products'&&<div className="search-field"><Search size={16}/><Input value={query} placeholder="Buscar SKU ou produto" aria-label="Buscar custos" onChange={e=>setQuery(e.target.value)}/></div>}</div>{tab==='products'?<DataTable data={latest} empty="Importe sua primeira planilha para começar." columns={[
 {accessorKey:'sku',header:'SKU'},
 {accessorKey:'description',header:'Produto',cell:({row})=><div className="product-cell"><div><strong>{row.original.description||'Sem descrição'}</strong><small>{accounts.find(a=>a.id===row.original.accountId)?.name}</small></div></div>},
 {accessorKey:'unitCost',header:'Custo unitário',cell:({getValue})=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:4}).format(Number(getValue()))},
 {accessorKey:'taxValue',header:'Imposto',cell:({row})=>row.original.taxValue===null?'Não informado':row.original.taxType==='percent'?`${row.original.taxValue}%`:money(Math.round(row.original.taxValue*100))},
 {accessorKey:'taxTreatment',header:'Tratamento',cell:({row})=><span className={row.original.taxTreatment==='unknown'?'pending-pill':'neutral-pill'}>{row.original.taxTreatment==='included'?'Incluído no custo':row.original.taxTreatment==='additional'?'Adicional':'A conferir'}</span>},
 {accessorKey:'validFrom',header:'Vigência',cell:({getValue})=>String(getValue()).split('-').reverse().join('/')}
 ]}/>:<DataTable data={imports} empty={demo?'Os exemplos não têm arquivos reais. Importe uma planilha na sua operação.':'Seu histórico de importações aparecerá aqui.'} columns={[
 {accessorKey:'filename',header:'Arquivo',cell:({row})=><div className="product-cell"><FileSpreadsheet size={18}/><div><strong>{row.original.filename}</strong><small>{new Date(row.original.createdAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></div></div>},
 {accessorKey:'rowCount',header:'Produtos'},{accessorKey:'validFrom',header:'Vigência',cell:({getValue})=>String(getValue()).split('-').reverse().join('/')},
 {id:'status',header:'Status',cell:({row})=><span className={row.original.withdrawnAt?'neutral-pill':'margin-pill'}>{row.original.withdrawnAt?'Retirado':'Ativo'}</span>},
 {id:'actions',header:'Ações',cell:({row})=><div className="inline-actions"><Button variant="ghost" size="icon" asChild><a href={`/api/imports/${row.original.id}`} aria-label={`Baixar ${row.original.filename}`}><Download size={16}/></a></Button>{!row.original.withdrawnAt&&<Button variant="ghost" size="icon" aria-label={`Retirar lote ${row.original.filename}`} onClick={()=>{setWithdraw(row.original);setError('')}}><Trash2 size={16}/></Button>}</div>}
 ]}/>}</section><div className="note"><Info size={16}/><p>A tabela mostra a última versão de cada produto. Cada venda usa o custo válido na sua data. Imposto já incluído no custo não é descontado novamente.</p></div>
 <AlertDialog open={!!withdraw} onOpenChange={v=>!busy&&!v&&setWithdraw(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Retirar este lote dos cálculos?</AlertDialogTitle><AlertDialogDescription>Os custos de {withdraw?.filename} deixarão de ser usados. A versão anterior volta a valer quando existir. O arquivo permanece no histórico.</AlertDialogDescription></AlertDialogHeader>{error&&<p className="error-box">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={()=>void remove()}>{busy?'Retirando…':'Retirar lote'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
