'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {visiblePoll} from '@/lib/visible-poll';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Store,Plus,Settings2,ShieldCheck,Copy,ExternalLink,RefreshCw,LoaderCircle,Unplug,Pause} from 'lucide-react';import {toast} from 'sonner';import type {Account} from '@/lib/demo';
type Connection={accountId:string;sellerId:string|null;nickname:string|null;status:string;syncedAt:number|null;syncStatus:string|null;syncMode:'history'|'incremental'|null;needsMore:boolean;processed:number|null;total:number|null;error:string|null};
type Status={automation:{state:string;heartbeatAt:number|null;lastEventAt:number|null;pending:number;error:string|null};app:{configured:boolean;secureReady:boolean;clientId:string;pkce:boolean;callbackUrl:string};connections:Connection[]};
async function api<T=Record<string,unknown>>(path:string,body?:unknown){const r=await fetch('/api/meli/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await r.json() as T & {error?:string};if(!r.ok)throw Error(data.error||'Não foi possível concluir.');return data;}
const statusLabel:Record<string,string>={connected:'Conectada',disconnected:'Desconectada',authorizing:'Autorização pendente',reconnect:'Reconectar',refreshing:'Renovando autorização'};
export function MeliAccounts({accounts,onAdd,onReload}:{accounts:Account[];onAdd:()=>void;onReload:()=>Promise<void>}){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[settings,setSettings]=useState(false),[busy,setBusy]=useState(''),[disconnect,setDisconnect]=useState<Account|null>(null);
 const [clientId,setClientId]=useState(''),[secret,setSecret]=useState(''),[pkce,setPkce]=useState(true),[saving,setSaving]=useState(false),[formError,setFormError]=useState('');
 const mounted=useRef(true),stop=useRef(false),loadingRequest=useRef(false);
 const load=useCallback(async()=>{if(loadingRequest.current)return;loadingRequest.current=true;try{const s=await api<Status>('status');if(mounted.current){setStatus(s);setError('');}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Não foi possível carregar as conexões.')}finally{loadingRequest.current=false}},[]);
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;stop.current=true}},[load]);
 useEffect(()=>visiblePoll(load),[load]);
 function openSettings(){if(!status)return;setClientId(status.app.clientId);setPkce(status.app.configured?status.app.pkce:true);setSecret('');setFormError('');setSettings(true)}
 async function save(){setSaving(true);setFormError('');try{await api('settings',{clientId,clientSecret:secret,pkce});setSecret('');await load();setSettings(false);toast.success('Aplicação configurada. Agora autorize sua conta.')}catch(e){setFormError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSaving(false)}}
 async function connect(id:string){setBusy(id);try{const result=await api<{url:string}>('connect',{accountId:id});window.location.assign(result.url)}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível iniciar.');setBusy('');await load()}}
 async function sync(id:string){setBusy(id);stop.current=false;try{while(!stop.current){const result=await api<{status:string;mode:'history'|'incremental';needsMore:boolean;processed:number;total:number}>('sync',{accountId:id});if(mounted.current)setStatus(s=>s?{...s,connections:s.connections.map(c=>c.accountId===id?{...c,processed:result.processed,total:result.total,syncStatus:result.status,syncMode:result.mode,needsMore:result.needsMore,error:null}:c)}:s);if(result.status==='complete'&&!result.needsMore){toast.success('Vendas atualizadas. Confira as margens e pendências.');break;}if(!mounted.current)break;}await onReload();}catch(e){toast.error(e instanceof Error?e.message:'A atualização foi interrompida. Você pode retomar.')}finally{if(mounted.current){setBusy('');await load();await onReload()}}}
 async function confirmDisconnect(){if(!disconnect)return;setBusy(disconnect.id);try{await api('disconnect',{accountId:disconnect.id});setDisconnect(null);await load();toast.success('Conexão encerrada. Custos e histórico preservados.')}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível desconectar.')}finally{setBusy('')}}
 return <><section className="accounts-heading"><div><h2>Suas contas, no mesmo lugar</h2><p>Conecte o vendedor à conta que já contém seus custos.</p></div><div className="inline-actions"><Button variant="outline" onClick={openSettings} disabled={!status||!!busy}><Settings2/>Configurar aplicação</Button><Button onClick={onAdd}><Plus/>Adicionar conta</Button></div></section>
 {error&&<div className="error-box" role="alert">{error}<Button variant="ghost" onClick={()=>void load()}>Tentar novamente</Button></div>}
 {!status&&!error&&<div className="panel loading-panel"><LoaderCircle className="animate-spin"/>Carregando conexões…</div>}
 {status&&!status.app.configured&&<section className="connection-note"><ShieldCheck size={24}/><div><h3>Ative sua aplicação do Mercado Livre</h3><p>Cadastre o endereço de retorno no portal e salve as credenciais aqui. Depois, autorize o vendedor de cada conta.</p><Button variant="outline" onClick={openSettings}>Configurar conexão <ExternalLink size={15}/></Button></div></section>}
 <div className="account-grid">{accounts.map(a=>{const c=status?.connections.find(c=>c.accountId===a.id),connected=c?.status==='connected'||c?.status==='refreshing',active=busy===a.id;return <section className="panel account-card" key={a.id}><div className="account-card-top"><span className="store-icon"><Store size={26}/></span><span className={connected?'margin-pill':'neutral-pill'}>{c?statusLabel[c.status]??'A conferir':'Não conectada'}</span></div><h2>{a.name}</h2><p>{c?.nickname?`${c.nickname} · vendedor ${c.sellerId}`:'Mercado Livre · Brasil'}</p><div className="account-status"><ShieldCheck size={16}/>{c?.syncedAt?'Atualizada em '+new Date(c.syncedAt).toLocaleString('pt-BR'):'Custos e impostos da sua planilha'}</div>
 {c?.syncStatus&&<div className="sync-progress" aria-live="polite"><p>{c.syncStatus==='complete'&&!c.needsMore?(c.syncMode==='incremental'?'Alterações recentes atualizadas':'Carga inicial concluída'):active?'Atualizando vendas…':'Atualização parcial · retome para concluir'}</p><strong>{c.processed??0} de {c.total??'…'} pedidos</strong><progress aria-label="Progresso da atualização" max={Math.max(1,c.total??1)} value={c.processed??0}/></div>}
 {c?.error&&<p className="warning-box">{c.error}</p>}
 <p className="note-text">{connected?'A primeira carga traz 30 dias. Depois, atualizamos as alterações recentes. Custos ligados pelo SKU desta conta.':'A autorização usa a aplicação configurada e preserva os custos já importados.'}</p>
 <div className="meli-card-actions">{connected?<Button onClick={()=>void sync(a.id)} disabled={!!busy}>{active?<LoaderCircle className="animate-spin"/>:<RefreshCw/>}{active?'Atualizando…':c?.syncStatus&&(c.syncStatus!=='complete'||c.needsMore)?'Retomar atualização':'Atualizar vendas'}</Button>:<Button onClick={()=>void connect(a.id)} disabled={!!busy||!status?.app.configured}>{active?<LoaderCircle className="animate-spin"/>:<ExternalLink/>}{c?.sellerId?'Reconectar conta':'Conectar Mercado Livre'}</Button>}{active&&connected?<Button variant="outline" onClick={()=>{stop.current=true;toast.info('A atualização será pausada ao terminar este lote.')}}><Pause/>Pausar</Button>:c&&c.status!=='disconnected'&&<Button variant="ghost" aria-label={'Desconectar '+a.name} disabled={!!busy} onClick={()=>setDisconnect(a)}><Unplug size={16}/></Button>}</div></section>})}</div>
 <section className="connection-note"><ShieldCheck size={22}/><div><h3>{status?.automation.state==='active'?(status.automation.lastEventAt?'Atualização automática funcionando':'Recuperação automática funcionando'):status?.automation.state==='lagging'?'Serviço automático sem contato recente':status?.automation.state==='retrying'?'Atualização automática em recuperação':'Atualização automática aguardando ativação'}</h3><p>{status?.automation.state==='pending'?'A ativação do serviço ainda precisa ser concluída. Enquanto isso, use Atualizar vendas e mantenha esta tela aberta.':'O serviço busca alterações mesmo com o app fechado. Com o painel aberto, os dados são consultados a cada 15 segundos. A entrega dos avisos pode sofrer atrasos do Mercado Livre.'}</p>{status?.automation.heartbeatAt&&<p className="note-text">Último contato: {new Date(status.automation.heartbeatAt).toLocaleString('pt-BR')} · {status.automation.pending} trabalhos pendentes.</p>}{status?.automation.state==='active'&&<p className="note-text">{status.automation.lastEventAt?'Último aviso recebido: '+new Date(status.automation.lastEventAt).toLocaleString('pt-BR'):'Recuperação periódica ativa. Aguardando o primeiro aviso do Mercado Livre.'}</p>}{status?.automation.error&&<p className="warning-box">{status.automation.error}</p>}<p className="note-text">A venda pode aparecer antes de concluir frete, descontos e margem. Custos e impostos seguem a vigência da planilha; vendas anteriores aguardam uma base histórica. Publicidade e despesas fixas ainda não compõem o resultado.</p></div></section>
 <Dialog open={settings} onOpenChange={v=>{if(!saving){setSettings(v);if(!v)setSecret('')}}}><DialogContent className="meli-settings"><DialogHeader><DialogTitle>Configurar aplicação</DialogTitle><DialogDescription>Use sua aplicação cadastrada no portal de desenvolvedores do Mercado Livre. As credenciais ficam protegidas no servidor.</DialogDescription></DialogHeader>
 <div className="meli-setup-step"><strong>1. Cadastre este endereço de retorno</strong><p>No portal, use exatamente este endereço como Redirect URI.</p><div className="copy-field"><Input aria-label="Endereço de retorno" value={status?.app.callbackUrl??''} readOnly onFocus={e=>e.target.select()}/><Button size="icon" variant="outline" aria-label="Copiar endereço de retorno" onClick={async()=>{try{await navigator.clipboard.writeText(status?.app.callbackUrl??'');toast.success('Endereço copiado.')}catch{toast.info('Selecione o endereço e copie.')}}}><Copy size={16}/></Button></div><a className="text-action" href="https://developers.mercadolivre.com.br/devcenter" target="_blank" rel="noreferrer">Abrir portal do Mercado Livre <ExternalLink size={13}/></a></div>
 <div className="meli-setup-step"><strong>2. Informe as credenciais da aplicação</strong><label className="form-label">Client ID<Input inputMode="numeric" autoComplete="off" value={clientId} onChange={e=>setClientId(e.target.value)} maxLength={30}/></label><label className="form-label">Client Secret<Input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} maxLength={500} placeholder={status?.app.configured?'Informe novamente para substituir a configuração':'Cole o segredo da aplicação'}/></label><label className="meli-checkbox"><input type="checkbox" checked={pkce} onChange={e=>setPkce(e.target.checked)}/>PKCE está ativado na minha aplicação</label><p className="note-text">A opção deve corresponder ao portal. Habilite acesso aos recursos de vendas e envios e a autorização com renovação de acesso (offline access).</p></div>
 <div className="meli-setup-step"><strong>3. Salve e conecte sua conta</strong><p>Após salvar, use “Conectar Mercado Livre” no cartão da loja e entre com o administrador do vendedor.</p></div>
 {!status?.app.secureReady&&<p className="error-box">A proteção do servidor ainda precisa ser configurada.</p>}{formError&&<p className="error-box" role="alert">{formError}</p>}<div className="dialog-actions"><Button variant="ghost" disabled={saving} onClick={()=>{setSettings(false);setSecret('')}}>Cancelar</Button><Button disabled={saving||!status?.app.secureReady||!/^\d{3,30}$/.test(clientId)||secret.trim().length<8} onClick={()=>void save()}>{saving&&<LoaderCircle className="animate-spin"/>}Salvar aplicação</Button></div></DialogContent></Dialog>
 <Dialog open={!!disconnect} onOpenChange={open=>!open&&setDisconnect(null)}><DialogContent><DialogHeader><DialogTitle>Desconectar {disconnect?.name}?</DialogTitle><DialogDescription>Novas consultas serão interrompidas. Seus custos e vendas já importados ficam preservados. Para revogar também a permissão no Mercado Livre, remova a aplicação nas configurações da sua conta por lá.</DialogDescription></DialogHeader><div className="dialog-actions"><Button variant="ghost" onClick={()=>setDisconnect(null)} disabled={!!busy}>Cancelar</Button><Button onClick={()=>void confirmDisconnect()} disabled={!!busy}>Desconectar</Button></div></DialogContent></Dialog></>;
}
