'use client';
import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Choice} from './commerce-controls';
import {money,type CostRecord,type Sale,type SalesChannel} from '@/lib/finance';
import {productTargetKey,type ReconciliationEvent} from '@/lib/reconciliation';
import type {Account} from '@/lib/demo';
import {businessDate} from '@/lib/dates';
import {LoaderCircle,PackageCheck,Save,TriangleAlert} from 'lucide-react';
import {toast} from 'sonner';

const channelLabel:Record<SalesChannel,string>={unknown:'Detectar pelo Mercado Livre',full:'Mercado Livre Full',other:'Venda comum'};
const sourceLabel={meli:'Mercado Livre',manual:'Ajuste da venda',product:'Configuração do anúncio',unknown:'Sem classificação'} as const;
function activeProductLink(events:ReconciliationEvent[],sale:Sale){if(!sale.itemId)return undefined;const target=productTargetKey(sale.itemId,sale.variationId);const latestByDate=new Map<string,ReconciliationEvent>();for(const event of events.filter(row=>row.accountId===sale.accountId&&row.targetType==='product'&&row.targetKey===target)){const saved=latestByDate.get(event.validFrom);if(!saved||event.revision>saved.revision)latestByDate.set(event.validFrom,event);}return [...latestByDate.values()].filter(event=>event.validFrom<=sale.date&&event.action==='set'&&event.payload?.kind==='product').sort((a,b)=>b.validFrom.localeCompare(a.validFrom)||b.revision-a.revision)[0];}

export function ProductLogisticsDialog({account,sku,sales,costs,events,demo,onReload,onClose}:{account?:Account;sku:string;sales:Sale[];costs:CostRecord[];events:ReconciliationEvent[];demo:boolean;onReload:()=>Promise<void>;onClose:()=>void}){
 const offers=useMemo(()=>{const map=new Map<string,Sale>();for(const sale of sales.filter(row=>row.accountId===account?.id&&row.sku===sku&&row.itemId)){const key=productTargetKey(sale.itemId!,sale.variationId);const current=map.get(key);if(!current||sale.date>current.date)map.set(key,sale);}return [...map.values()].sort((a,b)=>(a.itemId??'').localeCompare(b.itemId??'')||(a.variationId??'').localeCompare(b.variationId??''));},[account?.id,sales,sku]);
 const [selectedKey,setSelectedKey]=useState(()=>offers[0]?.itemId?productTargetKey(offers[0].itemId,offers[0].variationId):'');const selected=offers.find(row=>row.itemId&&productTargetKey(row.itemId,row.variationId)===selectedKey)??offers[0];
 const currentLink=useMemo(()=>selected?activeProductLink(events,selected):undefined,[events,selected]);
 const accountCosts=useMemo(()=>Object.values(costs.filter(cost=>cost.accountId===account?.id).reduce((all,cost)=>{const saved=all[cost.sku];if(!saved||cost.validFrom>saved.validFrom||cost.validFrom===saved.validFrom&&cost.importedAt>saved.importedAt)all[cost.sku]=cost;return all},{} as Record<string,CostRecord>)).sort((a,b)=>a.sku.localeCompare(b.sku,'pt-BR')),[account?.id,costs]);
 const [costSku,setCostSku]=useState(selected?.costSku??(accountCosts.some(cost=>cost.sku===sku)?sku:accountCosts[0]?.sku??''));const [channel,setChannel]=useState<SalesChannel>(currentLink?.payload?.kind==='product'?currentLink.payload.channel??'unknown':'unknown');const [validFrom,setValidFrom]=useState(currentLink?.validFrom??businessDate());const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 function choose(key:string){setSelectedKey(key);const row=offers.find(item=>item.itemId&&productTargetKey(item.itemId,item.variationId)===key);if(!row)return;const latest=activeProductLink(events,row);setCostSku(row.costSku??(accountCosts.some(cost=>cost.sku===sku)?sku:accountCosts[0]?.sku??''));setChannel(latest?.payload?.kind==='product'?latest.payload.channel??'unknown':'unknown');setValidFrom(latest?.validFrom??businessDate());setError('');}
 async function save(){if(!selected?.itemId||!account)return;if(!costSku){setError('Selecione o SKU de custo.');return;}if(reason.trim().length<3){setError('Explique o motivo da configuração.');return;}const target=productTargetKey(selected.itemId,selected.variationId);const expectedRevision=events.filter(event=>event.accountId===account.id&&event.targetType==='product'&&event.targetKey===target&&event.validFrom===validFrom).reduce((revision,event)=>Math.max(revision,event.revision),0);setBusy(true);setError('');try{const response=await fetch('/api/reconciliation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'product',action:'set',requestId:crypto.randomUUID(),accountId:account.id,itemId:selected.itemId,variationId:selected.variationId??null,validFrom,expectedRevision,sku:costSku,channel,reason:reason.trim()})});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error);await onReload();toast.success('Anúncio configurado e vendas recalculadas.');}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível salvar a configuração.')}finally{setBusy(false)}}
 return <DialogContent className="product-logistics-dialog"><DialogHeader><DialogTitle>Configurar anúncios de {sku}</DialogTitle><DialogDescription>{account?.name} · cada anúncio e variação mantém sua própria modalidade.</DialogDescription></DialogHeader>
  {demo&&<p className="info-box">A demonstração é somente leitura.</p>}
  {offers.length?<><div className="offer-list" role="list" aria-label="Anúncios deste produto">{offers.map(offer=>{const key=productTargetKey(offer.itemId!,offer.variationId);return <button type="button" role="listitem" className={key===selectedKey?'active':''} key={key} onClick={()=>choose(key)}><span><strong>{offer.itemId}</strong><small>{offer.variationId?`Variação ${offer.variationId}`:'Sem variação'}</small></span><span className={offer.operation?.conflict?'pending-pill':offer.operation?.channel==='full'?'margin-pill':'neutral-pill'}>{offer.operation?.conflict?'Revisar':channelLabel[offer.operation?.channel??'unknown']}</span></button>})}</div>
  {selected&&<section className="offer-editor"><div className="offer-summary"><PackageCheck size={19}/><div><strong>{selected.itemId}{selected.variationId?` · ${selected.variationId}`:''}</strong><p>Classificação efetiva: {channelLabel[selected.operation?.channel??'unknown']} · origem {sourceLabel[selected.operation?.source??'unknown']}</p><p>Vínculo atual: {selected.costSku??'sem SKU de custo'}{selected.linkValidFrom?` desde ${selected.linkValidFrom.split('-').reverse().join('/')}`:''}</p></div></div>{selected.operation?.conflict&&<div className="warning-box"><TriangleAlert size={17}/><p>{selected.operation.conflict}</p></div>}<div className="form-grid"><label>SKU de custo<Choice label="SKU de custo do anúncio" value={costSku||'none'} onChange={value=>setCostSku(value==='none'?'':value)} options={[{value:'none',label:'Selecionar SKU'},...accountCosts.map(cost=>({value:cost.sku,label:`${cost.sku} · ${cost.description||'Sem descrição'} · ${money(Math.round(cost.unitCost*100))}`}))]}/></label><label>Modalidade esperada<Choice label="Modalidade esperada" value={channel} onChange={value=>setChannel(value as SalesChannel)} options={(Object.keys(channelLabel) as SalesChannel[]).map(value=>({value,label:channelLabel[value]}))}/></label><label>Válido a partir de<Input type="date" value={validFrom} onChange={event=>setValidFrom(event.target.value)}/></label></div><label className="form-label">Motivo<Textarea maxLength={240} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Ex.: anúncio separado para estoque Full"/></label></section>}</>:<p className="info-box">Nenhum anúncio identificado nas vendas deste produto.</p>}
  {error&&<p className="error-box" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={onClose}>Fechar</Button><Button disabled={demo||busy||!selected||reason.trim().length<3||!costSku} onClick={()=>void save()}>{busy?<LoaderCircle className="animate-spin"/>:<Save/>}Salvar configuração</Button></div>
 </DialogContent>;
}
