import {z} from 'zod';import {commitImportBatch,type SavedImport} from '@/lib/import-commit';import {owner,database,bucket,digest,errorResponse,HttpError} from '@/lib/server';import {readWorkbook} from '@/lib/workbook';import {normalizeRows} from '@/lib/imports';
const column=z.number().int().min(-1).max(199);
const configSchema=z.object({accountId:z.string().uuid(),validFrom:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v),taxType:z.enum(['unit','percent']),taxTreatment:z.enum(['included','additional','unknown']),sheet:z.string().min(1).max(100),headerRow:z.number().int().min(1).max(20),mapping:z.object({sku:column.refine(v=>v>=0),cost:column.refine(v=>v>=0),description:column,tax:column})});
export async function POST(request:Request){try{
 const user=await owner(request);if(Number(request.headers.get('content-length')??0)>6*1024*1024)throw new HttpError(413,'Arquivo maior que o limite de 5 MB.');
 const form=await request.formData();const file=form.get('file');if(!(file instanceof File)||file.size>5*1024*1024||file.size===0)throw new HttpError(400,'Envie um arquivo CSV ou XLSX de até 5 MB.');
 let decoded:unknown;try{decoded=JSON.parse(String(form.get('config')))}catch{throw new HttpError(400,'Configuração inválida.')}
 const parsed=configSchema.safeParse(decoded);if(!parsed.success)throw new HttpError(400,'Revise a conta, a data e as colunas selecionadas.');const config=parsed.data;const db=database();
 const account=await db.prepare('SELECT id FROM accounts WHERE id=? AND owner_id=?').bind(config.accountId,user).first();if(!account)throw new HttpError(404,'Conta não encontrada.');
 const used=[config.mapping.sku,config.mapping.cost,config.mapping.description,config.mapping.tax].filter(i=>i>=0);if(new Set(used).size!==used.length)throw new HttpError(400,'Cada campo precisa de uma coluna diferente.');
 const buffer=await file.arrayBuffer();let sheets;try{sheets=readWorkbook(buffer,file.name)}catch(e){throw new HttpError(400,e instanceof Error?e.message:'Planilha inválida.')}
 const selected=sheets.find(s=>s.name===config.sheet);if(!selected)throw new HttpError(400,'Aba não encontrada.');const rows=selected.rows.slice(config.headerRow);if(rows.filter(row=>row.some(v=>String(v??'').trim()!=='')).length>5000)throw new HttpError(400,'Importe até 5.000 produtos por arquivo.');
 const normalized=normalizeRows(rows,config.mapping,config);if(normalized.issues.length)throw new HttpError(400,`Linha ${normalized.issues[0].row+config.headerRow}: ${normalized.issues[0].message}`);if(!normalized.records.length)throw new HttpError(400,'Nenhum produto válido no arquivo.');
 const fingerprint=await digest((await digest(buffer))+JSON.stringify(config));const existing=await db.prepare('SELECT id,withdrawn_at AS withdrawnAt FROM imports WHERE owner_id=? AND fingerprint=?').bind(user,fingerprint).first();if(existing){if(existing.withdrawnAt)throw new HttpError(409,'Este lote foi retirado. Altere a vigência ou envie um arquivo revisado para criar outro lote.');return Response.json({id:existing.id,duplicate:true});}
 const id=crypto.randomUUID();const now=new Date().toISOString();const fileKey=`imports/${id}`;await bucket().put(fileKey,buffer,{httpMetadata:{contentType:/\.csv$/i.test(file.name)?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}});
 const statements=[db.prepare('INSERT INTO imports(id,owner_id,account_id,filename,file_key,fingerprint,config,valid_from,row_count,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,user,config.accountId,file.name.replace(/[\r\n/\\]/g,'_').slice(0,200),fileKey,fingerprint,JSON.stringify(config),config.validFrom,normalized.records.length,now)];
 for(let start=0;start<normalized.records.length;start+=8){const chunk=normalized.records.slice(start,start+8);const values=chunk.flatMap(c=>[crypto.randomUUID(),user,config.accountId,id,c.sku,c.description,c.unitCost,c.taxValue,c.taxType,c.taxTreatment,c.validFrom,now]);statements.push(db.prepare(`INSERT INTO cost_versions(id,owner_id,account_id,import_id,sku,description,unit_cost,tax_value,tax_type,tax_treatment,valid_from,imported_at) VALUES ${chunk.map(()=>'(?,?,?,?,?,?,?,?,?,?,?,?)').join(',')}`).bind(...values));}
 const recovered=await commitImportBatch({id,commit:()=>db.batch(statements),findSaved:()=>db.prepare('SELECT id,withdrawn_at AS withdrawnAt FROM imports WHERE owner_id=? AND fingerprint=?').bind(user,fingerprint).first<SavedImport>(),discard:()=>bucket().delete(fileKey)});
 if(recovered?.withdrawnAt)throw new HttpError(409,'Este lote foi retirado. Altere a vigência ou envie um arquivo revisado para criar outro lote.');
 if(recovered)return Response.json({id:recovered.id,duplicate:true});
 return Response.json({id,rowCount:normalized.records.length},{status:201});
 }catch(e){return errorResponse(e)}}
