import {sqliteTable,text,real,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const meliApps=sqliteTable('meli_apps',{ownerId:text('owner_id').primaryKey(),clientId:text('client_id').notNull(),secret:text('secret').notNull(),pkce:integer('pkce').notNull(),revision:text('revision').notNull(),updatedAt:integer('updated_at').notNull()});
export const meliConnections=sqliteTable('meli_connections',{accountId:text('account_id').primaryKey().references(()=>accounts.id),ownerId:text('owner_id').notNull(),sellerId:text('seller_id'),nickname:text('nickname'),status:text('status').notNull(),generation:text('generation').notNull(),tokens:text('tokens'),expiresAt:integer('expires_at'),refreshStarted:integer('refresh_started'),updatedAt:integer('updated_at').notNull(),syncedAt:integer('synced_at'),syncCursor:text('sync_cursor'),grossSalesVersion:integer('gross_sales_version').notNull().default(1),logisticsVersion:integer('logistics_version').notNull().default(1),financialsVersion:integer('financials_version').notNull().default(1)},t=>[uniqueIndex('idx_meli_owner_seller').on(t.ownerId,t.sellerId),index('idx_meli_connections_owner').on(t.ownerId)]);
export const meliOauthStates=sqliteTable('meli_oauth_states',{stateHash:text('state_hash').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),browserHash:text('browser_hash').notNull(),verifier:text('verifier').notNull(),generation:text('generation').notNull(),appRevision:text('app_revision').notNull(),expiresAt:integer('expires_at').notNull()});
export const meliSyncRuns=sqliteTable('meli_sync_runs',{accountId:text('account_id').primaryKey().references(()=>accounts.id),ownerId:text('owner_id').notNull(),generation:text('generation').notNull(),id:text('id').notNull(),mode:text('mode').notNull().default('history'),needsMore:integer('needs_more').notNull().default(0),fromDate:text('from_date').notNull(),toDate:text('to_date').notNull(),offset:integer('offset').notNull(),total:integer('total'),status:text('status').notNull(),lease:text('lease'),leaseUntil:integer('lease_until'),error:text('error'),updatedAt:integer('updated_at').notNull()});
export const meliOrders=sqliteTable('meli_orders',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),orderId:text('order_id').notNull(),date:text('date').notNull(),data:text('data').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('idx_meli_account_order').on(t.accountId,t.orderId),index('idx_meli_orders_owner_date').on(t.ownerId,t.date)]);
export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_accounts_owner').on(t.ownerId)]);
export const imports=sqliteTable('imports',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),filename:text('filename').notNull(),fileKey:text('file_key').notNull(),fingerprint:text('fingerprint').notNull(),config:text('config').notNull(),validFrom:text('valid_from').notNull(),rowCount:integer('row_count').notNull(),createdAt:text('created_at').notNull(),withdrawnAt:text('withdrawn_at')},t=>[index('idx_imports_owner_date').on(t.ownerId,t.createdAt),uniqueIndex('idx_imports_owner_fingerprint').on(t.ownerId,t.fingerprint)]);
export const costVersions=sqliteTable('cost_versions',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),importId:text('import_id').notNull().references(()=>imports.id),sku:text('sku').notNull(),description:text('description').notNull(),unitCost:real('unit_cost').notNull(),taxValue:real('tax_value'),taxType:text('tax_type').notNull(),taxTreatment:text('tax_treatment').notNull(),validFrom:text('valid_from').notNull(),importedAt:text('imported_at').notNull()},t=>[index('idx_costs_owner_account_sku_date').on(t.ownerId,t.accountId,t.sku,t.validFrom),index('idx_costs_import').on(t.importId)]);
export const reconciliationEvents=sqliteTable('reconciliation_events',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),targetType:text('target_type').notNull(),targetKey:text('target_key').notNull(),validFrom:text('valid_from').notNull().default(''),revision:integer('revision').notNull(),requestId:text('request_id').notNull(),action:text('action').notNull(),payload:text('payload'),sourceStamp:text('source_stamp'),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_reconciliation_owner_request').on(t.ownerId,t.requestId),uniqueIndex('idx_reconciliation_target_revision').on(t.ownerId,t.accountId,t.targetType,t.targetKey,t.validFrom,t.revision),index('idx_reconciliation_owner_account').on(t.ownerId,t.accountId,t.createdAt)]);
export const fullClosureEvents=sqliteTable('full_closure_events',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),month:text('month').notNull(),revision:integer('revision').notNull(),requestId:text('request_id').notNull(),action:text('action').notNull(),totalExpenseCents:integer('total_expense_cents'),eligibleUnits:integer('eligible_units').notNull(),sourceStamp:text('source_stamp'),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},table=>[
 uniqueIndex('idx_full_closure_owner_request').on(table.ownerId,table.requestId),
 uniqueIndex('idx_full_closure_revision').on(table.ownerId,table.accountId,table.month,table.revision),
 index('idx_full_closure_owner_month').on(table.ownerId,table.accountId,table.month),
]);
export const fullClosureAllocations=sqliteTable('full_closure_allocations',{closureId:text('closure_id').notNull().references(()=>fullClosureEvents.id),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),saleId:text('sale_id').notNull(),units:integer('units').notNull(),expenseCents:integer('expense_cents').notNull()},table=>[
 uniqueIndex('idx_full_allocation_closure_sale').on(table.closureId,table.saleId),
 index('idx_full_allocation_owner_account').on(table.ownerId,table.accountId),
]);
export const meliAccountLeases=sqliteTable('meli_account_leases',{accountId:text('account_id').primaryKey().references(()=>accounts.id),ownerId:text('owner_id').notNull(),generation:text('generation').notNull(),lease:text('lease').notNull(),leaseUntil:integer('lease_until').notNull()});
export const meliJobs=sqliteTable('meli_jobs',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),generation:text('generation').notNull(),resource:text('resource').notNull(),revision:integer('revision').notNull().default(1),attempts:integer('attempts').notNull().default(0),dueAt:integer('due_at').notNull(),lease:text('lease'),leaseUntil:integer('lease_until'),error:text('error'),updatedAt:integer('updated_at').notNull()},t=>[index('idx_meli_jobs_due').on(t.dueAt),index('idx_meli_jobs_account').on(t.accountId)]);
export const meliAutomationNonces=sqliteTable('meli_automation_nonces',{nonce:text('nonce').primaryKey(),expiresAt:integer('expires_at').notNull()},t=>[index('idx_meli_nonces_expiry').on(t.expiresAt)]);
export const meliAutomationHealth=sqliteTable('meli_automation_health',{id:text('id').primaryKey(),heartbeatAt:integer('heartbeat_at').notNull(),eventAt:integer('event_at')});
export const adProfileEvents=sqliteTable('ad_profile_events',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),itemId:text('item_id').notNull(),variationId:text('variation_id').notNull().default(''),validFrom:text('valid_from').notNull(),revision:integer('revision').notNull(),requestId:text('request_id').notNull(),action:text('action').notNull(),payload:text('payload'),origin:text('origin').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},table=>[
 uniqueIndex('idx_ad_profiles_owner_request').on(table.ownerId,table.requestId),
 uniqueIndex('idx_ad_profiles_target_revision').on(table.ownerId,table.accountId,table.itemId,table.variationId,table.validFrom,table.revision),
 index('idx_ad_profiles_owner_account').on(table.ownerId,table.accountId,table.itemId,table.variationId,table.validFrom),
]);
export const saleCorrectionEvents=sqliteTable('sale_correction_events',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),saleId:text('sale_id').notNull(),field:text('field').notNull(),revision:integer('revision').notNull(),requestId:text('request_id').notNull(),action:text('action').notNull(),mode:text('mode').notNull(),value:integer('value'),sourceValue:integer('source_value'),sourceStamp:text('source_stamp').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},table=>[
 uniqueIndex('idx_sale_corrections_owner_request').on(table.ownerId,table.requestId),
 uniqueIndex('idx_sale_corrections_target_revision').on(table.ownerId,table.accountId,table.saleId,table.field,table.revision),
 index('idx_sale_corrections_owner_account').on(table.ownerId,table.accountId,table.saleId),
]);
export const meliListings=sqliteTable('meli_listings',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),accountId:text('account_id').notNull().references(()=>accounts.id),itemId:text('item_id').notNull(),variationId:text('variation_id').notNull().default(''),title:text('title').notNull(),status:text('status').notNull(),sellerSku:text('seller_sku'),seenGeneration:text('seen_generation').notNull(),updatedAt:integer('updated_at').notNull()},table=>[
 uniqueIndex('idx_meli_listings_target').on(table.ownerId,table.accountId,table.itemId,table.variationId),
 index('idx_meli_listings_owner_account').on(table.ownerId,table.accountId,table.status),
]);
export const meliCatalogRuns=sqliteTable('meli_catalog_runs',{accountId:text('account_id').primaryKey().references(()=>accounts.id),ownerId:text('owner_id').notNull(),generation:text('generation').notNull(),id:text('id').notNull(),offset:integer('offset').notNull(),total:integer('total'),status:text('status').notNull(),lease:text('lease'),leaseUntil:integer('lease_until'),error:text('error'),updatedAt:integer('updated_at').notNull()},table=>[
 index('idx_meli_catalog_runs_owner').on(table.ownerId,table.status),
]);
export const adProfileRollouts=sqliteTable('ad_profile_rollouts',{ownerId:text('owner_id').primaryKey(),state:text('state').notNull(),sourceStamp:text('source_stamp').notNull(),report:text('report').notNull(),activatedAt:text('activated_at'),updatedAt:text('updated_at').notNull()});
